### ISSUE TITLE
Fix padding tests to reflect inset padding

### ISSUE THREAD

**Issue by spoeschel** [IRT-Open-Source/irt-ebu-tt-d-application-samples#11]
As follow-up of the discussion in https://github.com/w3c/ttml1/issues/221, the padding tests have to be revised in order to reflect that the [TTML padding](https://www.w3.org/TR/ttaf1-dfxp/#style-attribute-padding) is an _inset_ padding.

**Comment by andreastai** [comment]
Thanks to @palemieux for spotting this bug.
